steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.cloudrun
      - -t
      - ${_IMAGE}
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - .
    dir: frontend
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-southeast1-docker.pkg.dev/tech-496413/techcare-free-trial/techcare-app:latest
  _VITE_API_BASE_URL: https://api.techcare.site